// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockPort(arg1) {
  return window['go']['main']['App']['BlockPort'](arg1);
}

export function GetBaselineStatus() {
  return window['go']['main']['App']['GetBaselineStatus']();
}

export function GetProcessInfo(arg1) {
  return window['go']['main']['App']['GetProcessInfo'](arg1);
}

export function KillPort(arg1) {
  return window['go']['main']['App']['KillPort'](arg1);
}

export function ListBaselines() {
  return window['go']['main']['App']['ListBaselines']();
}

export function ScanAndCompare(arg1) {
  return window['go']['main']['App']['ScanAndCompare'](arg1);
}

export function ShowCriticalToast(arg1) {
  return window['go']['main']['App']['ShowCriticalToast'](arg1);
}

export function ShowToast(arg1, arg2) {
  return window['go']['main']['App']['ShowToast'](arg1, arg2);
}

export function UpdateTrayIcon(arg1) {
  return window['go']['main']['App']['UpdateTrayIcon'](arg1);
}

export function WhitelistPort(arg1) {
  return window['go']['main']['App']['WhitelistPort'](arg1);
}
