// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlockPort(arg1:string):Promise<string>;

export function GetBaselineStatus():Promise<string>;

export function GetProcessInfo(arg1:number):Promise<string>;

export function KillPort(arg1:string):Promise<string>;

export function ListBaselines():Promise<string>;

export function ScanAndCompare(arg1:string):Promise<string>;

export function ShowCriticalToast(arg1:string):Promise<string>;

export function ShowToast(arg1:string,arg2:string):Promise<string>;

export function UpdateTrayIcon(arg1:number):Promise<void>;

export function WhitelistPort(arg1:string):Promise<string>;
